// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.MeetingTimeConverter
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("originalTime")]
        public string OriginalTime { get; set; }

        [JsonProperty("convertedTime")]
        public DateTimeOffset ConvertedTime { get; set; }

        [JsonProperty("fromTimezone")]
        public string FromTimezone { get; set; }

        [JsonProperty("toTimezone")]
        public string ToTimezone { get; set; }

        [JsonProperty("timeDifference")]
        public long TimeDifference { get; set; }

        [JsonProperty("fromOffset")]
        public string FromOffset { get; set; }

        [JsonProperty("toOffset")]
        public string ToOffset { get; set; }
    }
}
